version: '3.8'

services:
  quantum-ml-noiseless:
    build: .
    container_name: quantum-ml-noiseless
    volumes:
      - ./results:/app/results
    environment:
      - ENVIRONMENT=noiseless
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'